FROM quay.io/aptible/debian:stretch

# cf. docker-library/mysql: explicitly create the user so uid and gid are consistent.
RUN groupadd -r mysql && useradd -r -g mysql mysql

ENV MYSQL_VERSION <%= ENV.fetch 'MYSQL_VERSION' %>
ENV MYSQL_PACKAGE_VERSION <%= ENV.fetch 'MYSQL_PACKAGE_VERSION' %>
ENV MYSQL_PERFORMANCE_SCHEMA <%= ENV.fetch 'MYSQL_PERFORMANCE_SCHEMA' %>

# We need gnupg for apt-key
RUN apt-get update \
 && apt-get install -y gnupg \
 && rm -rf /var/lib/apt/lists/*

ADD <%= ENV.fetch 'TAG' %>/templates/etc/apt/sources.list.d /etc/apt/sources.list.d

# Getting keys from keyservers tends to fail in Travis, so we want to retry.
ADD bin/retry /usr/bin/

RUN retry apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 5072E1F5 && \
    apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
        faketime \
        netcat \
        perl \
        procps \
        "mysql-server=${MYSQL_PACKAGE_VERSION}" \
        "mysql-client=${MYSQL_PACKAGE_VERSION}" \
        python-minimal \
        && \
    rm -rf /var/lib/apt/lists/*


ENV CONF_DIRECTORY /etc/mysql
RUN rm -r "$CONF_DIRECTORY"
ADD templates/etc/mysql $CONF_DIRECTORY
ADD <%= ENV.fetch 'TAG' %>/templates/etc/mysql $CONF_DIRECTORY

ENV DATA_DIRECTORY /var/db
ENV LOG_DIRECTORY /var/log/mysql
ENV SCRATCH_DIRECTORY /var/scratch
RUN mkdir -p "$DATA_DIRECTORY" "$LOG_DIRECTORY" "$SCRATCH_DIRECTORY" \
 && chown -R mysql:mysql "$DATA_DIRECTORY" "$LOG_DIRECTORY" "$SCRATCH_DIRECTORY" \
 && chmod 700 "$SCRATCH_DIRECTORY"

ADD bin/run-database.sh /usr/bin/
ADD bin/utilities.sh /usr/bin/
ADD bin/autotune /usr/local/bin/

ADD test /tmp/test
ADD <%= ENV.fetch 'TAG' %>/test /tmp/test

VOLUME ["$DATA_DIRECTORY"]
EXPOSE 3306

ENTRYPOINT ["run-database.sh"]
